
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS LPAREN NAME NUMBER PLUS RPARENexpression : expression PLUS termexpression : termterm : factorfactor : LPAREN expression RPARENexpression : NAME EQUALS expressionfactor : NUMBERfactor : NAME'
    
_lr_action_items = {'NAME':([0,5,7,8,],[3,3,11,3,]),'LPAREN':([0,5,7,8,],[5,5,5,5,]),'NUMBER':([0,5,7,8,],[6,6,6,6,]),'$end':([1,2,3,4,6,10,11,12,13,],[0,-2,-7,-3,-6,-1,-7,-5,-4,]),'PLUS':([1,2,3,4,6,9,10,11,12,13,],[7,-2,-7,-3,-6,7,-1,-7,7,-4,]),'RPAREN':([2,3,4,6,9,10,11,12,13,],[-2,-7,-3,-6,13,-1,-7,-5,-4,]),'EQUALS':([3,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,8,],[1,9,12,]),'term':([0,5,7,8,],[2,2,10,2,]),'factor':([0,5,7,8,],[4,4,4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parser.py',14),
  ('expression -> term','expression',1,'p_expression_term','parser.py',19),
  ('term -> factor','term',1,'p_term_factor','parser.py',24),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','parser.py',29),
  ('expression -> NAME EQUALS expression','expression',3,'p_expression_equals','parser.py',34),
  ('factor -> NUMBER','factor',1,'p_factor_number','parser.py',41),
  ('factor -> NAME','factor',1,'p_factor_name','parser.py',46),
]
