
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS LPAREN NAME NUMBER PLUS RPARENexpression : expression PLUS termexpression : termterm : factorexpression : expression EQUALS termfactor : LPAREN expression RPARENfactor : NUMBERfactor : NAME'
    
_lr_action_items = {'LPAREN':([0,4,7,8,],[4,4,4,4,]),'NUMBER':([0,4,7,8,],[5,5,5,5,]),'NAME':([0,4,7,8,],[6,6,6,6,]),'$end':([1,2,3,5,6,10,11,12,],[0,-2,-3,-6,-7,-1,-4,-5,]),'PLUS':([1,2,3,5,6,9,10,11,12,],[7,-2,-3,-6,-7,7,-1,-4,-5,]),'EQUALS':([1,2,3,5,6,9,10,11,12,],[8,-2,-3,-6,-7,8,-1,-4,-5,]),'RPAREN':([2,3,5,6,9,10,11,12,],[-2,-3,-6,-7,12,-1,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,4,],[1,9,]),'term':([0,4,7,8,],[2,2,10,11,]),'factor':([0,4,7,8,],[3,3,3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parser.py',9),
  ('expression -> term','expression',1,'p_expression_term','parser.py',14),
  ('term -> factor','term',1,'p_term_factor','parser.py',19),
  ('expression -> expression EQUALS term','expression',3,'p_expression_equals','parser.py',24),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','parser.py',29),
  ('factor -> NUMBER','factor',1,'p_factor_num','parser.py',34),
  ('factor -> NAME','factor',1,'p_factor_name','parser.py',39),
]
